[package]
name = "apriltag"
version = "0.1.0"
authors = ["EtomicBomb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.23.2"

[build-dependencies]
bindgen = "0.54.0"
