[package]
name = "detect"
version = "0.1.0"
authors = ["EtomicBomb <ethan@ethan.ws>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
palette = "0.5.0"
arrayvec = "0.5.2"
ordered-float = "2.0.1"